parameters:
#    reservacion.example.class: ProyUser\ReservacionBundle\Example

services:
#    reservacion.example:
#        class: %reservacion.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
