parameters:
#    autenticacion.example.class: ProyUser\AutenticacionBundle\Example

services:
#    autenticacion.example:
#        class: %autenticacion.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
