parameters:
#    rms_marcaciones.example.class: ProyUser\RmsMarcacionesBundle\Example

services:
#    rms_marcaciones.example:
#        class: %rms_marcaciones.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
