security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_USER:        ROLE_USER
        ROLE_ADMIN:       ROLE_ADMIN
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

#    providers:
#        in_memory:
#            memory:
#                users:
#                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
#                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    providers:
        main:
            entity:
                class:  ProyUser\UsuarioBundle\Entity\Persona
                property: user


    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

#        login:
#            pattern:  ^/demo/secured/login$
#            security: false


#        login:
#            pattern: ^/login$
#            security: false
#        login:
#            pattern: ^/home$
#            security: false


        secured_area:
            pattern:    ^/
            anonymous:  ~
            form_login:
                check_path: autenticacion_login_check
                login_path: autenticacion_login
            logout:
                path:   /logout
                target: /
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

#         secured_area:
#             pattern:    ^/*
#             form_login:
#                 check_path: autenticacion_login_check
#                 login_path: autenticacion_login
#                 always_use_default_target_path: true
#                 default_target_path: /
#
#             logout:
#                 path:   /logout
#                 target: /
#             anonymous: ~
             #http_basic:
             #    realm: "Secured Demo Area"


    access_control:
        - { path: ^/perfil, roles: ROLE_USER }
        - { path: ^/rms/*, roles: ROLE_USER}

#     access_control:
#        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
#        - { path: ^/home, roles: IS_AUTHENTICATED_ANONYMOUSLY}
#        - { path: ^/correo, roles: ROLE_PROFESOR}
#        - { path: ^/browser, roles: ROLE_PROFESOR}
#        - { path: ^/gestionarET/*, roles:[ ROLE_JDPTO,ROLE_ADMIN,ROLE_VFORMACION]}
#        - { path: ^/gestionarCC/*, roles:[ ROLE_JDPTO,ROLE_ADMIN,ROLE_JASIG,ROLE_VFORMACION]}
#        - { path: ^/gestionarPF/*, roles:[ ROLE_ADMIN,ROLE_VFORMACION]}
#        - { path: ^/browser, roles: ROLE_JDPTO}
#        - { path: ^/admin, roles: ROLE_ADMIN}
#        - { path: ^/browser, roles: ROLE_JASIG}
#        - { path: ^/admin, roles: ROLE_VFORMACION}
